apiVersion: v1
kind: Secret
metadata:
  namespace: x402-function
  name: x402-function-backend-secret
type: Opaque
stringData:
  HIVE_API_BASE_URL: ""
  HIVE_API_ACCOUNT: ""
  HIVE_API_TOKEN: ""
  HIVE_API_TOKEN_HEADER_NAME: ""
